trigger:
  - main

variables:
  - template: .pipelines/config.variables.yml

stages:
  - template: .pipelines/build.stage.yml
  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: 'azSubValue'
      environmentType: devType
      appName: ${{ variables.appName }}
      resourceGroupName: resource-group-name
  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: 'azSubValue'
      environmentType: QA
      appName: ${{ variables.appName }}
      resourceGroupName: resource-group-name
      dependsOn: deployStage$(devType)

#  - stage: devDeployStage
#    displayName: Dev
#    dependsOn: buildAppStage
#    jobs:
#      - job: productionSlotJob
#        displayName: 'Production Slot'
#        steps:
#          - script: |
#              echo 'download artifact'
#            displayName: 'download artifact'
#          - script: |
#              echo 'webApp deploy staging'
#            displayName: 'webApp deploy staging'
#          - script: |
#              echo 'smokeTest staging'
#            displayName: 'smokeTest staging'

#      - job: SwapEast
#        displayName: 'Swap East Slot'
#        dependsOn: productionSlotJob
#        steps:
#          - script: |
#              echo 'swapSlots production'
#            displayName: 'swapSlots production'
#          - script: |
#              echo 'smokeTest production'
#            displayName: 'smokeTest production'
#
#  - stage: qaDeployStage
#    displayName: QA
#    dependsOn: devDeployStage
#    jobs:
#      - job: productionSlotJob
#        displayName: 'Production Slot'
#        steps:
#          - script: |
#              echo 'download artifact'
#            displayName: 'download artifact'
#          - script: |
#              echo 'webApp deploy staging'
#            displayName: 'webApp deploy staging'
#          - script: |
#              echo 'smokeTest staging'
#            displayName: 'smokeTest staging'
#
#      - job: SwapEast
#        displayName: 'Swap East Slot'
#        dependsOn: productionSlotJob
#        steps:
#          - script: |
#              echo 'swapSlots production'
#            displayName: 'swapSlots production'
#          - script: |
#              echo 'smokeTest production'
#            displayName: 'smokeTest production'
