trigger:
- main

pr:
- main

variables:
  - template: .pipelines/config.variables.yml

stages:
  - template: .pipelines/build.stage.yml

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeDev }}
      dependsOn: buildStage
      disabled: in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeQa }}
      dependsOn: deployStage${{ variables.environmentTypeDev }}

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeProd }}
      dependsOn: deployStage${{ variables.environmentTypeQa }}
