trigger:
  - main

variables:
  - template: .pipelines/config.variables.yml

stages:
  - template: .pipelines/build.stage.yml

  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: 'azSubValue'
      environmentType: ${{ variables.devType }}
      appName: ${{ variables.appName }}
      resourceGroupName: resource-group-name
      dependsOn: buildStage

  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: 'azSubValue'
      environmentType: QA
      appName: ${{ variables.appName }}
      resourceGroupName: resource-group-name
      dependsOn: deployStage${{ variables.devType }}
