trigger:
- main

pr:
- main

variables:
  - template: .pipelines/config.variables.yml

stages:
  - template: .pipelines/build.stage.yml

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeDev }}
      dependsOn: buildStage
      disabled: ${{ not(variables['isCI']) }}

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeQa }}
      dependsOn: deployStage${{ variables.environmentTypeDev }}

  - stage: deployStage${{ parameters.environmentType }}
    displayName: ${{ parameters.environmentType }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: and(succeeded(), eq('${{ parameters.disabled }}', false))
    jobs:
    - template: stagingSlot.job.yml
      parameters:
        environmentType: ${{ parameters.environmentType }}

  - stage: deployProd${{ parameters.environmentType }}
    displayName: ${{ parameters.environmentType }}
    dependsOn: deployStage${{ parameters.environmentType }}
    jobs:
    - template: prodSlot.job.yml
      parameters:
        environmentType: ${{ parameters.environmentType }}
