trigger:
- main

pr:
- main

variables:
  - template: .pipelines/config.variables.yml

stages:
  - template: .pipelines/build.stage.yml

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeDev }}
      dependsOn: buildStage
      disabled: ${{ not(variables['isCI']) }}

  - template: .pipelines/deploy.stage.yml
    parameters:
      environmentType: ${{ variables.environmentTypeQa }}
      dependsOn: deployStage${{ variables.environmentTypeDev }}

  - template: .pipelines/deployProd.stage.yml
    parameters:
      dependsOn: deployStage${{ variables.environmentTypeQa }}