trigger:
  - main

variables:
  - template: .pipelines/config.variables.yml

stages:
  - template: .pipelines/build.stage.yml

  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: ${{ variables.azureSubscription }}
      environmentType: ${{ variables.environmentTypeDev }}
      appName: ${{ variables.appName }}
      resourceGroupName: ${{ variables.resourceGroupName }}
      dependsOn: buildStage

  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: ${{ variables.azureSubscription }}
      environmentType: ${{ variables.environmentTypeQa }}
      appName: ${{ variables.appName }}
      resourceGroupName: ${{ variables.resourceGroupName }}
      dependsOn: deployStage${{ variables.environmentTypeDev }}

  - template: .pipelines/deploy.stage.yml
    parameters:
      azureSubscription: ${{ variables.azureSubscription }}
      environmentType: ${{ variables.environmentTypeProd }}
      appName: ${{ variables.appName }}
      resourceGroupName: ${{ variables.resourceGroupName }}
      dependsOn: deployStage${{ variables.environmentTypeQa }}
