stages:
- stage: buildStage
  displayName: Build and Test
  jobs:
    - job: buildAppJob
      displayName: Build
      steps:
        - script: |
            echo 'buildStage'
            echo ${{ notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}
            echo ${{ variables['isCI'] }}
          displayName: Build
        - script: |
            echo 'publishArtifact'
          displayName: Publish Artifact

    - job: testAppJob
      displayName: Unit Tests
      dependsOn: buildAppJob
      steps:
        - script: |
            echo 'runLint'
          displayName: Lint Code
        - script: |
            echo 'runUnitTests'
          displayName: Unit Tests
        - script: |
            echo 'publishTestCoverage'
          displayName: Publish Code Coverage