stages:
- stage: buildStage
  displayName: Build and Test
  jobs:
    - job: buildAppJob
      displayName: Build
      variables:
      - template: config.variables.yml
      steps:
        - script: |
            echo 'buildStage'
            echo isCI-manual - ${{ in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}
            echo isCI-${{ variables.isCI }}
          displayName: Build
        - script: |
            echo 'publishArtifact'
          displayName: Publish Artifact

    - job: testAppJob
      displayName: Unit Tests
      dependsOn: buildAppJob
      steps:
        - script: |
            echo 'runLint'
          displayName: Lint Code
        - script: |
            echo 'runUnitTests'
          displayName: Unit Tests
        - script: |
            echo 'publishTestCoverage'
          displayName: Publish Code Coverage