variables:
  # project configs
  appName: appNameValue
  resourceGroupName: resource-group-name
  azureSubscription: azSubValue

  # constant helpers
  isPR: ${{ notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}
  urlStaging: https://$(appName).azurewebsites.net/system/health
  urlProd: https://$(appName).azurewebsites.net/system/health

  # constant configs
  environmentTypeDev: Dev
  environmentTypeQa: QA
  environmentTypeProd: Prod
