variables:
  # project configs
  appName: appNameValue
  resourceGroupName: resource-group-name
  azureSubscription: azSubValue

  # constant helpers
#  isSourceBranch: ne(variables['Build.SourceBranchName'], 'master')
  isCI: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  # constant configs
  environmentTypeDev: Dev
  environmentTypeQa: QA
  environmentTypeProd: Prod
