variables:
  # project configs
  appName: appNameValue
  resourceGroupName: resource-group-name
  azureSubscription: azSubValue

  # constant configs
  environmentTypeDev: Dev
  environmentTypeQa: QA
  environmentTypeProd: Prod