variables:
  # project configs
  appName: appNameValue
  resourceGroupName: resource-group-name
  azureSubscription: azSubValue

  # constant helpers
#  isSourceBranch: ne(variables['Build.SourceBranchName'], 'master')
  isCI: ${{ in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}

  # constant configs
  environmentTypeDev: Dev
  environmentTypeQa: QA
  environmentTypeProd: Prod
