variables:
  # project configs
  appName: appNameValue
  resourceGroupName: resource-group-name
  azureSubscription: azSubValue

  # constant helpers
#  isCI: ${{ in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}
  isCI: ${{ true }}  # TODO: unmock

  # constant configs
  environmentTypeDev: Dev
  environmentTypeQa: QA
  environmentTypeProd: Prod
