parameters:
  - name: 'type'
    type: string
    values:
      - Dev
      - QA
      - Prod
  - name: 'azureSubscription'
    type: 'string'

stages:
- stage: devDeployStage
  displayName: ${{ parameters.type }}
  dependsOn: buildAppStage
  jobs:
    - job: stagingSlotJob
      displayName: Staging Slot
      steps:
        - script: |
            echo 'download artifact'
          displayName: Download Artifact
        - script: |
            echo 'webApp deploy staging'
            echo azureSubscription-${{ parameters.azureSubscription }}
          displayName: Deploy Staging

    - job: smokeTestStaging
      displayName: Smoke Test
      steps:
        - script: |
            echo 'smokeTest staging'
          displayName: SmokeTest

    - job: productionSlotJob
      displayName: Production Slot
      steps:
        - script: |
            echo 'swapSlots production'
          displayName: SwapSlots Production

    - job: smokeTestProduction
      displayName: Smoke Test
      steps:
        - script: |
            echo 'smokeTest production'
          displayName: SmokeTest Production
