parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod
  - name: dependsOn
    type: string

variables:
  - template: config.variables.yml

stages:
- stage: deployStage${{ parameters.environmentType }}
  displayName: ${{ parameters.environmentType }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
    - job: stagingSlotJob
      displayName: Staging Slot
      steps:
        - script: |
            echo 'download artifact'
          displayName: Download Artifact
        - script: |
            echo 'webApp deploy staging'
            echo azureSubscription-${{ variables.azureSubscription }}
            echo appName-${{ variables.appName }}
          displayName: Deploy Staging

    - template: smokeTest.job.yml
      parameters:
        type: Staging
        urls: urlsValue-staging
        appName: ${{ variables.appName }}

    - job: productionSlotJob
      displayName: Production Slot
      steps:
        - script: |
            echo 'swapSlots production'
            echo resourceGroupName-${{ variables.resourceGroupName }}
          displayName: SwapSlots Production

    - template: smokeTest.job.yml
      parameters:
        type: Prod
        urls: urlsValue-prod
        appName: ${{ variables.appName }}
