parameters:
  - name: 'type'
    type: string
  - name: 'azureSubscription'
    type: 'string'

stages:
- stage: devDeployStage
  displayName: ${{ parameters.type }}
  dependsOn: buildAppStage
  jobs:
    - job: stagingSlotJob
      displayName: Staging Slot
      steps:
        - script: |
            echo 'download artifact'
          displayName: Download Artifact
        - script: |
            echo 'webApp deploy staging'
            echo azureSubscription-${{ parameters.azureSubscription }}
          displayName: Deploy Staging
        - script: |
            echo 'smokeTest staging'
          displayName: SmokeTest Staging
    - job: productionSlotJob
      displayName: Production Slot
      steps:
        - script: |
            echo 'swapSlots production'
          displayName: SwapSlots Production
        - script: |
            echo 'smokeTest production'
          displayName: SmokeTest Production
