parameters:
- name: dependsOn
  type: string

variables:
- template: .pipelines/config.variables.yml

stages:
- stage: deployProdSlotStaging${{ variables.environmentTypeProd }}
  displayName: ${{ variables.environmentTypeProd }} - Staging
  dependsOn: deployStage${{ variables.environmentTypeQA }}
  jobs:
  - template: stagingSlot.job.yml
    parameters:
      environmentType: ${{ variables.environmentTypeProd }}

- stage: deployProdSlotProd${{ variables.environmentTypeProd }}
  displayName: ${{ variables.environmentTypeProd }} - Live
  dependsOn: deployProdSlotStaging${{ variables.environmentTypeProd }}
  jobs:
  - template: prodSlot.job.yml
    parameters:
      environmentType: ${{ variables.environmentTypeProd }}
