parameters:
  - name: 'azureSubscription'
    type: string
  - name: 'type'
    type: string
    values:
      - Dev
      - QA
      - Prod
  - name: 'appName'
    type: string
  - name: resourceGroupName
    type: string

stages:
- stage: devDeployStage
  displayName: ${{ parameters.type }}
  dependsOn: buildAppStage
  jobs:
    - job: stagingSlotJob
      displayName: Staging Slot
      steps:
        - script: |
            echo 'download artifact'
          displayName: Download Artifact
        - script: |
            echo 'webApp deploy staging'
            echo azureSubscription-${{ parameters.azureSubscription }}
            echo appName-${{ parameters.appName }}
          displayName: Deploy Staging

    - template: .pipelines/smokeTest.job.yml
      parameters:
        urls: urlsValue

    - job: productionSlotJob
      displayName: Production Slot
      steps:
        - script: |
            echo 'swapSlots production'
            echo resourceGroupName-${{ parameters.resourceGroupName }}
          displayName: SwapSlots Production

    - job: smokeTestProduction
      displayName: Production Smoke Test
      steps:
        - script: |
            echo 'smokeTest production'
          displayName: SmokeTest Production
