parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod
  - name: dependsOn
    type: string
  - name: disabled
    type: boolean
    default: false

stages:
- stage: deployStage${{ parameters.environmentType }}
  displayName: ${{ parameters.environmentType }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: and(succeeded(), not('${{ parameters.disabled }}'))

  variables:
    - template: config.variables.yml
  jobs:
    - deployment: StagingSlotJob
      displayName: Staging Slot
      pool:
        vmImage: 'ubuntu-latest'
      environment: ${{ parameters.environmentType }}
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo 'webApp deploy staging'
                echo azureSubscription-${{ variables.azureSubscription }}
                echo appName-${{ variables.appName }}
                echo disabled-${{ variables.disabled }}
            - template: smokeTest.step.yml
              parameters:
                type: Staging
                appName: ${{ variables.appName }}

    - deployment: ProdSlotJob
      displayName: Prod Slot
      dependsOn: StagingSlotJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: ${{ parameters.environmentType }}
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo 'webApp deploy staging'
                echo azureSubscription-${{ variables.azureSubscription }}
                echo appName-${{ variables.appName }}
            - template: smokeTest.step.yml
              parameters:
                type: Prod
                appName: ${{ variables.appName }}


#    - job: StagingSlotJob
#      displayName: Staging Slot
#      steps:
#        - script: |
#            echo 'download artifact'
#          displayName: Download Artifact
#        - script: |
#            echo 'webApp deploy staging'
#            echo azureSubscription-${{ variables.azureSubscription }}
#            echo appName-${{ variables.appName }}
#          displayName: Deploy Staging
#
#    - template: smokeTest.step.yml
#      parameters:
#        type: Staging
#        urls: urlsValue-staging
#        appName: ${{ variables.appName }}
#        dependsOn: stagingSlotJob

#    - job: ProdSlotJob
#      displayName: Production Slot
#      dependsOn: smokeTestStaging
#      steps:
#        - script: |
#            echo 'swapSlots production'
#            echo resourceGroupName-${{ variables.resourceGroupName }}
#          displayName: SwapSlots Production
#
#    - template: smokeTest.step.yml
#      parameters:
#        type: Prod
#        urls: urlsValue-prod
#        appName: ${{ variables.appName }}
#        dependsOn: prodSlotJob
