parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod
  - name: dependsOn
    type: string
  - name: disabled
    type: boolean
    default: false

stages:
- stage: deployStage${{ parameters.environmentType }}
  displayName: ${{ parameters.environmentType }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: and(succeeded(), eq('${{ parameters.disabled }}', false))
  jobs:
    - template: stagingSlot.job.yml
      parameters:
        environmentType: ${{ parameters.environmentType }}

    - template: prodSlot.job.yml
      parameters:
        environmentType: ${{ parameters.environmentType }}
        dependsOn: StagingSlotJob
