parameters:
- name: environmentType
  type: string
  values:
  - Dev
  - QA
  - Prod
- name: dependsOn
  type: string
  default: ''

jobs:
- deployment: ProdSlotJob
  displayName: Prod Slot
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environmentType }}
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            echo 'webApp deploy staging'
            echo azureSubscription-${{ variables.azureSubscription }}
            echo appName-${{ variables.appName }}
        - template: smokeTest.step.yml
          parameters:
            type: Prod
            appName: ${{ variables.appName }}